### ISSUE TITLE
Ganzes Programm bugt.

### ISSUE THREAD

**Issue by jancodet** [KingKevin23/agspiel-python-api#27]
**Erklärung des Bugs**
Joa läuft halt nicht.
**So kann man ihn reproduzieren**
Irgendwie stürzt mein PC ab..

**Erwartetes Verhalten**
PC sollte nicht abstürzen..
Wollte Minecraft spielen

**Screenshots**
Kein Monitor vorhanden.

**Desktop (bitte die folgenden Informationen ausfüllen):**
 - Betriebssystem: Linux Debian Jessy
 - Python-Version 1.1
 - API-Version 0.2.1

**Sonstiger Kontext**
Kp bist nen schlechter Infomann
LG Passy und Jan

**Comment by KingKevin23** [comment]
Das Problem liegt hier vor dem Gerät

**Comment by KingKevin23** [comment]
Das Problem liegt hier vor dem Gerät :-)

**Comment by jancodet** [comment]
Find ich Pietätlos einen hilflosen Benutzer so bloß zustellen.
Im Folgenden eine Liste für das nächste Issue und dessen Beantwortung:

- Analysieren des Problems
- Zerlegen in Teilprobleme
- Abstrahieren
- Zu guter Letzt: Freundlich antworten

LG

**Comment by KingKevin23** [comment]
🥉
